let quotes = [
"Stay focused and never give up.",
"Success is built daily.",
"Discipline beats motivation.",
"Small steps lead to big results.",
"Believe in yourself.",
"Dream big, work hard.",
"Push yourself every day.",
"Consistency is the key.",
"Your only limit is you.",
"Start now, not later.",
"Work until you’re proud.",
"Stay positive, work hard.",
"Success needs patience.",
"Be stronger than excuses.",
"Make it happen.",
"Don’t stop until you win.",
"Effort brings success.",
"Stay hungry, stay foolish.",
"Do it with passion.",
"Keep going no matter what.",
"Great things take time.",
"Focus on progress.",
"Never quit.",
"Hard work pays off.",
"Turn dreams into reality.",
"Be fearless.",
"Work smart and hard.",
"Stay dedicated.",
"Success loves discipline.",
"Keep moving forward.",
"Believe and achieve.",
"Rise and grind.",
"Stay committed.",
"Your future is created today.",
"Win your morning.",
"Stay determined.",
"Chase your goals.",
"Make every day count.",
"Push beyond limits.",
"Stay unstoppable.",
"Dream it, do it.",
"Stay focused, stay sharp.",
"Success is a journey.",
"Never lose hope.",
"Keep improving.",
"Stay resilient.",
"Be consistent.",
"Think big.",
"Stay motivated.",
"Take action now.",
"Make yourself proud.",
"Stay strong.",
"Don’t give up.",
"Stay confident.",
"Build your future.",
"Work for it.",
"Stay disciplined.",
"Be bold.",
"Keep pushing.",
"Stay inspired.",
"Trust the process.",
"Stay hungry.",
"Be the best version of you.",
"Never back down.",
"Stay patient.",
"Keep learning.",
"Stay focused always.",
"Make progress daily.",
"Stay determined always.",
"Do your best.",
"Keep chasing greatness.",
"Stay energized.",
"Stay committed daily.",
"Success starts now.",
"Stay powerful.",
"Never stop growing.",
"Stay ambitious.",
"Push harder.",
"Stay driven.",
"Stay focused on goals.",
"Be unstoppable.",
"Keep the fire alive.",
"Stay on track.",
"Never settle.",
"Stay positive always.",
"Keep aiming higher.",
"Stay consistent daily.",
"Be unstoppable force.",
"Stay motivated always.",
"Keep winning.",
"Stay productive.",
"Stay strong daily.",
"Keep believing.",
"Stay focused daily.",
"Never lose focus.",
"Stay active.",
"Stay dedicated daily.",
"Keep achieving.",
"Stay sharp.",
"Stay confident always."
];
function newQuote() {
    let random = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText = quotes[random];
}